### ISSUE TITLE
Responsive Ads

### ISSUE THREAD

**Issue by zlever01** [BlackBoxVision/next-google-dfp#1]
Is there an example of how to setup responsive ads with next-google-dfp?

**Comment by 2xSamurai** [comment]
In slots define your sizes

`{
        divId: "div-id",
        slotId: "slot-id",
        sizeMappings: [[970, 250], [970, 90], [728, 90]],
    }`


And for the ad component try the following.


`<Ad id="banner-ad" width={'auto'} height={'auto'} />`

It worked for me. Hope it helps you as well.

**Comment by JonatanSalas** [comment]
Hi @2xSamurai thank you for helping @zlever01. We're soon going to work on a better documentation site and different example projects.
