### ISSUE TITLE
Lazyload / Create new Ad Slots dynamically

### ISSUE THREAD

**Issue by red1** [BlackBoxVision/next-google-dfp#3]
Hello
First great work on this component I was about to start building one myself when I found yours.
this is more a general question rather than a proper issue: Is there any guideline on how to use this package with lazy loaded ads : I've an infinite news and when I load new content I'd like to generate new slots and rerun the google tag cmd only for the newly created slots on the page?
Thanks
Redouane

**Comment by JonatanSalas** [comment]
Hi @red1, thank you very much for your appreciation on our work!!

There is a prop that's `enableLazyload` that you can define in the `AdsProvider`, with that prop setted to `true` we can change the way slots are created by enabling lazyloading.

Let me know if this helps you!

**Comment by red1** [comment]
but how do you pass the dynamically created div Ids to the component? The ad divs are all defined in the ads array in the config no ? 
```
ads =[
    {
      slotId: "/6355419/foo/bar/",
      sizeMappings: [[970, 250], [970, 90], [728, 90]],
      divId: "leaderboard",
    },
  ]; 
```
is it possible to push in that array the dynamic ids ?

**Comment by JonatanSalas** [comment]
Yes, you can push it with no trouble. We run a useEffect that watches for the changes over the `ads` array, so if the array has changed we re run and it should render the dynamically created ads.
